name: Tests & Qualite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installer python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Installer les dependances
        run: |
          pip install -r requirements.txt
          pip install flake8 pytest pytest-cov

      - name: Lancer les etapes sur dossier app et tests
        run: |
          flake8 app --count --select=E9,F63,F7,F82,f841 --show-source --statistics
          flake8 app --count --max-complexity=10 --max-line-length=127 --statistics
          flake8 tests --count --max-line-length=127 --statistics
      - name: Lancer les tests
        run: python -m pytest --cov=app tests/
